import type { Metadata } from "next";
import "@/styles/globals.css";
import LayoutContent from '@/components/layout/layout-content';

export const metadata: Metadata = {
  title: "Eagle Intuition",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <body>
        <LayoutContent>{children}</LayoutContent>
      </body>
    </html>
  );
}
