// app/layout.tsx (fichier serveur, PAS 'use client')

import '../styles/globals.css'
import LayoutClient from './layout.client'

export const metadata = {
  title: 'Eagle Intuition',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt">
      <body>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  )
}
